# Generated by Django 3.2.4 on 2023-01-17 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория объектов',
                'verbose_name_plural': 'Категории объектов',
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('qty_room', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('floor', models.CharField(blank=True, max_length=32, null=True, verbose_name='Этажность')),
                ('residence', models.CharField(blank=True, max_length=256, null=True, verbose_name='Жилой комплекс')),
                ('constructioт_company', models.CharField(blank=True, max_length=256, null=True, verbose_name='Строительная компания')),
                ('locate', models.CharField(blank=True, max_length=256, null=True, verbose_name='Расположение')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('repair', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ремонт')),
                ('document', models.CharField(blank=True, max_length=256, null=True, verbose_name='Документ')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('land_area', models.FloatField(blank=True, null=True, verbose_name='Площадь участка')),
                ('wall_material', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Материал стен')),
                ('additional_buildings', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Дополнительные построения')),
                ('communications', models.CharField(blank=True, max_length=512, null=True, verbose_name='Коммуникации')),
                ('is_separately', models.BooleanField(blank=True, null=True, verbose_name='Находится отдельно')),
                ('appointment', models.CharField(blank=True, max_length=512, null=True, verbose_name='Назначение')),
                ('lenght_width', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ширина и длина')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': ('Объект',),
                'verbose_name_plural': ('Объекты',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='pics', verbose_name='Изображение')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='realty.objects', verbose_name='Объект')),
            ],
            options={
                'verbose_name': ('Фото',),
                'verbose_name_plural': ('Фото',),
            },
        ),
    ]
